"""
codex_bot.features.errors
==========================
Built-in system error handling for Redis ``system_error`` events.

No extra dependencies — included in the base ``codex-bot`` install.

Quick start:
    ```python
    # 1. Add to your BotContainer:
    from codex_bot.features.errors import ErrorOrchestrator

    class BotContainer:
        def __init__(self, settings, redis_client):
            self.errors_orchestrator = ErrorOrchestrator(
                custom_errors=getattr(settings, "custom_errors", None),
            )

    # 2. Register the Redis router in your factory:
    from codex_bot.features.errors.handlers import redis_router as errors_router

    builder.include_redis_router(errors_router)
    ```

Extending the error map:
    ```python
    # core/errors.py (generated by `codex-bot startproject`):
    CUSTOM_ERRORS = {
        "payment_failed": {
            "title": "Payment Failed",
            "text": "Please try again.",
            "button_text": "Retry",
            "action": "retry_payment",
        },
    }
    ```

Custom UI renderer:
    ```python
    from codex_bot.features.errors import BaseErrorUI
    from codex_bot.base.view_dto import ViewResultDTO

    class MyErrorUI:
        def render_error(self, error_config: dict) -> ViewResultDTO:
            return ViewResultDTO(text=error_config["text"], kb=None)

    orchestrator = ErrorOrchestrator(ui=MyErrorUI())
    ```
"""

from .default_errors import DEFAULT_ERRORS
from .orchestrator import ErrorOrchestrator
from .ui import BaseErrorUI, DefaultErrorUI

__all__ = [
    "ErrorOrchestrator",
    "DefaultErrorUI",
    "BaseErrorUI",
    "DEFAULT_ERRORS",
]
